# Generated by Django 4.1.5 on 2023-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apPaterno', models.CharField(max_length=50)),
                ('apMaterno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=50)),
                ('confirmar_contraseña', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('catalogo', models.CharField(choices=[('bandanas', 'Bandana.'), ('arnes', 'Arnes.'), ('collar', 'Collares.'), ('identificadores', 'Identificadores.')], default='producto', max_length=25)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
