# Generated by Django 4.1.5 on 2023-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newPage', '0003_remove_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
